{"name": "新增客户失败-手机号格式不正确", "status": "failed", "statusDetails": {"message": "pytest_assume.plugin.FailedAssumption: \n1 Failed Assumptions:\n\nrun.py:120: AssumptionFailure\n>>\tpytest.assume(actual_res==expect_res,f'期望是{expect_res},实际是{actual_res}')\nAssertionError: 期望是1,实际是0\nassert False", "trace": "tp = <class 'pytest_assume.plugin.FailedAssumption'>, value = None, tb = None\n\n    def reraise(tp, value, tb=None):\n        try:\n            if value is None:\n                value = tp()\n            if value.__traceback__ is not tb:\n>               raise value.with_traceback(tb)\nE               pytest_assume.plugin.FailedAssumption: \nE               1 Failed Assumptions:\nE               \nE               run.py:120: AssumptionFailure\nE               >>\tpytest.assume(actual_res==expect_res,f'期望是{expect_res},实际是{actual_res}')\nE               AssertionError: 期望是1,实际是0\nE               assert False\n\nD:\\Programs\\Python\\python310\\lib\\site-packages\\six.py:718: FailedAssumption"}, "attachments": [{"name": "log", "source": "a5c7ba3b-9d97-4da7-81d5-eed43c85c255-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "suite_name", "value": "'新增客户接口测试集合'"}, {"name": "case_name", "value": "'新增客户失败-手机号格式不正确'"}, {"name": "case_info_list", "value": "[['新增客户', '${host}/CrmCustomer/addOrUpdate', 'post', '{\\n\"Admin-Token\":\"${token}\"\\n}', '{\\n\"json\":{\\n\"$.entity.mobile\":\"sddsdffd\",\\n}\\n}', '', 200, '[\\n{\\n\"actual\":\"$.code\",\\n\"expect\":1\\n}\\n]']]"}], "start": 1652325210872, "stop": 1652325210951, "uuid": "99638a24-b516-4562-89bd-69e6d742b098", "historyId": "fa56c786c679629df4954d9a99dd7aa5", "testCaseId": "581fcf0b30a85e3d611d5f9973144474", "fullName": "run#test_run", "labels": [{"name": "feature", "value": "新增客户接口测试集合"}, {"name": "suite", "value": "run"}, {"name": "host", "value": "LAPTOP-93HH27QA"}, {"name": "thread", "value": "17100-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "run"}]}